[package]
name = "baker"
version.workspace = true
edition.workspace = true


[dependencies]
metis = { path = "../metis" }
common = { path = "../common" }
petgraph.workspace = true
glam.workspace = true
idmap = "0.2"
rand = "0.8"
