[package]
name = "baker"
version.workspace = true
edition.workspace = true


[dependencies]
metis = { path = "../metis" }
common = { path = "../common" }
petgraph.workspace = true
glam.workspace = true
idmap = "0.2"
rand = "0.8"
bytemuck.workspace = true
priority-queue = "1.3"
indicatif = { version = "0.17", features = ["rayon"] }
anyhow = "1.0"
thiserror = "1.0"
rayon = "1.8"
