[package]
name = "common"
version.workspace = true
edition.workspace = true


[dependencies]
bincode = "2.0.0-rc.3"
serde = { version = "1.0", features = ["derive"] }
glam.workspace = true
bytemuck.workspace = true
gltf.workspace = true
petgraph.workspace = true
open = "5.0"
