[package]
name = "ash_renderer"
version.workspace = true
edition.workspace = true


[dependencies]
winit = "0.28"
env_logger.workspace = true
log.workspace = true
bytemuck.workspace = true
glam.workspace = true
gltf.workspace = true
pollster = "0.3"
bevy_ecs = "0.11"
common = { path = "../common" }
common_renderer = { path = "../common_renderer" }
ash = { version = "0.37", default-features = false, features = [
	"linked",
	"debug",
] }
ash-window = "0.12"
raw-window-handle = "0.5"
memoffset = "0.5.1"
num = "0.2.0"
tobj = "0.1.10"
image = "0.22"
shaderc = "0.8"


[profile.dev]
opt-level = 1


[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.5", features = ["windef", "libloaderapi"] }
